//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotDialog.Sample.PersonalInfoManger.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int content_discard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int content_edit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int content_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int content_new_event = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialog_expander_ic_minimized = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon_36 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon_48 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int navigation_accept = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int social_add_person = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spinner_default_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spinner_default_holo_light = 2130837515;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int detail_fragment = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int dialog_BoolField = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int dialog_Button = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int dialog_DisclosureField = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int dialog_HtmlField = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int dialog_ImageLeft = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int dialog_ImageRight = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int dialog_LabelField = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int dialog_LabelPercentageField = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int dialog_LabelSubtextField = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int dialog_Panel = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int dialog_RadioButtonList = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int dialog_SliderField = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int dialog_Spinner = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int dialog_ValueField = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int iFormFieldValue = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int list_view_Text = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int menu_add = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int menu_delete = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int menu_edit = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int menu_save = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int pager = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int pager_title_strip = 2131165202;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_achievements = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldleft = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldright = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubleft = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_boolfieldsubright = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_button = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_datefield = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_fieldsetlabel = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_floatimage = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_html = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labeldisclosure = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldbelow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_labelfieldright = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_multiline_labelfieldbelow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_onofffieldright = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_panel = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_root = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlist = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_selectlistfield = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textarea = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldbelow = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_textfieldright = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int list_view = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Main = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Splash = 2130903065;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int CalendarEventMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CalendarMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ContactListMenu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ContactMenu = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int CreateMenu = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int EditMenu = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int TaskListMenu = 2131099654;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationTheme = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
